openapi: 3.0.0
info:
  description: "## Overview\n\n\n## End Point\nhttp://localhost:8080/EpcBS\n## Headers\n- **serviceName** (string, required): Example:ProductDirectoryRegister\n- **msgId** (string, required): Example: MSGAA1728477388000175\n- **errors** (string, required)\n- **userId** (string, required): Example:admin\n\n## Request Parameters\n- **ProductDirectory** ((type:object))\n\t- **perspective** ((type:object))\n\t\t- **perspectiveCode** (mandatory: false, type:string, maxLength:10): Perspective Code\n\t- **xEffectiveFrom** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): Effective From\n\t- **xEffectiveTill** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): Effective Till\n\t- **xAsOn** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): As On\n\t- **xLastDate** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): Last Date\n\t- **xTimeSeriesStatus** (mandatory: false, type:string, maxLength:100): Time Series Status\n\t- **xChildId** (mandatory: false, type:string, maxLength:20): Child Id\n\t- **xStatus** (mandatory: false, type:string, maxLength:20, enum:[\"A\",\"D\",\"C\"]): Status\n\t- **xSuperId** (mandatory: false, type:string, maxLength:4000): Super Id\n\t- **xAbsDelta** (mandatory: false, type:string, maxLength:4000): Abosolute Delta\n\t- **ProductRefrence** ((type:object))\n\t\t- **ProductIdentification** ((type:object))\n\t\t\t- **IdentifierValue** ((type:object))\n\t\t\t\t- **value** (mandatory: false, pattern:^[a-zA-Z0-9_-]+$, type:string, maxLength:30): Value\n\t\t\t- **IdentifierStartDate** ((type:object))\n\t\t\t\t- **DateTimeContent** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): Date Time Content\n\t\t\t- **IdentifierEndDate** ((type:object))\n\t\t\t\t- **DateTimeContent** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): Date Time Content\n\t\t- **ProductType** (mandatory: false, type:string, maxLength:50): Product Type\n\t\t- **ProductName** ((type:object))\n\t\t\t- **Name** (mandatory: false, type:string, maxLength:50): Name\n\t\t- **IdentifierIssuingAuthority** ((type:object))\n\t\t\t- **PartyReference** ((type:object))\n\t\t\t\t- **PartyName** ((type:object))\n\t\t\t\t\t- **Name** (mandatory: false, type:integer): Name\n\t\t\t- **PartyDateTime** ((type:object))\n\t\t\t\t- **DateTimeContent** (mandatory: false, format:date-time, pattern:YYYY-MM-DDTHH:mm:ssZ, type:string): Date Time Content\n\t\t- **ProductLifecycleStatus** ((type:object))\n\t\t\t- **ProductLifecycleStatusType** (mandatory: false, type:string, maxLength:20, enum:[\"A\",\"D\",\"C\"]): Product Lifecycle Status Type\n\t\t- **ProductDescription** ((type:object))\n\t\t\t- **Text** (mandatory: false, type:string, maxLength:500): Text\n\t- **ProductDirectoryEntryConfiguration** ((type:object))\n\t\t- **ProductVersion** ((type:object))\n\t\t\t- **text** (mandatory: false, type:integer, minimum:1): Text\n\t- **ProductLifecycleStatus** ((type:object))\n\t\t- **StatusInvolvedParty** ((type:object))\n\t\t\t- **PartyInvolvement** ((type:object))\n\t\t\t\t- **PartyRoleType** (mandatory: false, type:string, maxLength:2, enum:[\"O\",\"S\",\"M\",\"I\"]): Party Role Type\n\t\t\t- **PartyRoleName** ((type:object))\n\t\t\t\t- **Name** (mandatory: false, type:integer): Name\n## Response Parameters\n## Additional Notes\n"
  title: "ProductDirectoryRegisterEntry"
  version: 1.0.0
servers:
  - url: http://localhost:8080/EpcBS
paths:
  /Rest/ProductDirectoryRegister:
    post:
      summary: Invoke ProductDirectoryRegister
      requestBody:
        $ref: "#/components/requestBodies/ProductDirectoryRegisterRequest"
      responses:
        "200":
          $ref: "#/components/responses/ProductDirectoryRegisterResponse"
components:
  requestBodies:
    ProductDirectoryRegisterRequest:
      description: Request payload for invoking ProductDirectoryRegister
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductDirectoryRegisterRequest"
  responses:
    ProductDirectoryRegisterResponse:
      description: Invoke ProductDirectoryRegister successful
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ProductDirectoryRegisterResponse"
  schemas:
    ProductDirectoryRegisterRequest:
      type: object
      description: Request wrapper for ProductDirectoryRegister
      properties:
        header:
          $ref: "#/components/schemas/Header"
        body:
          $ref: "#/components/schemas/ProductDirectoryRegisterRequestBody"
    ProductDirectoryRegisterResponse:
      type: object
      description: Response wrapper for ProductDirectoryRegister
      properties:
        roductDirectoryIdentification:
            type: string
            x-unique: true
            format: Identifier
            description: "A unique identifier for the Product Directory Entry"
            example: "507f1f77bcf86cd799439011" # Example MongoDB ObjectId
        header:
          $ref: "#/components/schemas/Header"
        body:
          $ref: "#/components/schemas/ProductDirectoryRegisterRequestBody"
    DateTimeString:
      type: string
      description: Date formatted as YYYY-MM-DDTHH:mm:ssZ
      format: date-time
      pattern: YYYY-MM-DDTHH:mm:ssZ
      example: 2025-01-01T00:00:00Z
    Header:
      type: object
      description: Standard request header
      properties:
        serviceName:
          type: string
          description: Name of the invoked service
          example: ProductDirectoryRegister
        userId:
          type: string
          description: Identifier of the invoking user
          example: admin
        msgId:
          type: string
          description: Unique identifier of the message
          example: MSGAA1728477388000175
    ProductDirectoryRegisterRequestBody:
      type: object
      description: Wrapper for ProductDirectory
      properties:
        ProductDirectory:
          $ref: "#/components/schemas/ProductDirectory"
    ProductDirectory:
      type: object
      description: Container of Product Directory details
      properties:
        perspective:
          $ref: "#/components/schemas/Perspective"
        xEffectiveFrom:
          $ref: "#/components/schemas/DateTimeString"
        xEffectiveTill:
          $ref: "#/components/schemas/DateTimeString"
        xAsOn:
          $ref: "#/components/schemas/DateTimeString"
        xLastDate:
          $ref: "#/components/schemas/DateTimeString"
        xTimeSeriesStatus:
          type: string
          description: Time Series Status
          maxLength: 100
          example: ACTIVE
        xChildId:
          type: string
          description: Child Id
          maxLength: 20
          example: CHD123
        xStatus:
          type: string
          description: Status
          maxLength: 20
          enum: [A,D,C]
          example: A
        xSuperId:
          type: string
          description: Super Id
          maxLength: 4000
          example: SUP456
        xAbsDelta:
          type: string
          description: Absolute Delta
          maxLength: 4000
          example: DELTA789
        ProductReference:
          $ref: "#/components/schemas/ProductReference"
        ProductDirectoryEntryConfiguration:
          $ref: "#/components/schemas/ProductDirectoryEntryConfiguration"
        ProductLifecycleStatus:
          $ref: "#/components/schemas/ProductLifecycleStatus"
    Perspective:
      type: object
      description: Perspective definition
      properties:
        perspectiveCode:
          type: string
          description: Perspective Code
          maxLength: 10
          example: PERS001
    ProductReference:
      type: object
      description: Reference to a product
      properties:
        ProductIdentification:
          $ref: "#/components/schemas/ProductIdentification"
        ProductType:
          type: string
          description: Type of product
          maxLength: 50
          example: Loan
        ProductName:
          $ref: "#/components/schemas/ProductName"
        IdentifierIssuingAuthority:
          $ref: "#/components/schemas/IdentifierIssuingAuthority"
        ProductLifecycleStatus:
          $ref: "#/components/schemas/ProductLifecycleStatusType"
        ProductDescription:
          $ref: "#/components/schemas/ProductDescription"
    ProductIdentification:
      type: object
      description: Identification details of product
      properties:
        IdentifierValue:
          $ref: "#/components/schemas/IdentifierValue"
        IdentifierStartDate:
          $ref: "#/components/schemas/IdentifierStartDate"
        IdentifierEndDate:
          $ref: "#/components/schemas/IdentifierEndDate"
    IdentifierValue:
      type: object
      description: Identifier value
      properties:
        value:
          type: string
          description: Identifier textual value
          maxLength: 30
          pattern: ^[a-zA-Z0-9_-]+$
          example: PROD123
    IdentifierStartDate:
      type: object
      description: Start date of identifier
      properties:
        DateTimeContent:
          $ref: "#/components/schemas/DateTimeString"
    IdentifierEndDate:
      type: object
      description: End date of identifier
      properties:
        DateTimeContent:
          $ref: "#/components/schemas/DateTimeString"
    ProductName:
      type: object
      description: Name of the product
      properties:
        Name:
          type: string
          description: Word or phrase that constitutes the designation of the product
          format: DataType
          example: Personal Loan
    IdentifierIssuingAuthority:
      type: object
      description: Authority that issued the identifier
      properties:
        PartyReference:
          $ref: "#/components/schemas/PartyReference"
        PartyDateTime:
          $ref: "#/components/schemas/PartyDateTime"
    PartyReference:
      type: object
      description: Reference to a party
      properties:
        PartyName:
          $ref: "#/components/schemas/PartyName"
    PartyName:
      type: object
      description: Name by which a party is known and which is usually used to identify that party. ISO20022
      properties:
        Name:
          type: integer
          description: Numeric designation of a party
          example: 1001
    PartyDateTime:
      type: object
      description: Date and time associated with a party
      properties:
        DateTimeContent:
          $ref: "#/components/schemas/DateTimeString"
    ProductLifecycleStatusType:
      type: string
      description: Product Lifecycle Status Type
      maxLength: 20
      enum: [A,D,C]
      example: A
    ProductDescription:
      type: object
      description: Description of the product
      properties:
        Text:
          type: string
          description: Free text description of product
          maxLength: 500
          example: Consumer personal loan product
    ProductDirectoryEntryConfiguration:
      type: object
      description: Configuration of product directory entry
      properties:
        ProductVersion:
          $ref: "#/components/schemas/ProductVersion"
    ProductVersion:
      type: object
      description: Version of the product
      properties:
        text:
          type: integer
          description: Product version number
          minimum: 1
          example: 1
    ProductLifecycleStatus:
      type: object
      description: Lifecycle status container
      properties:
        StatusInvolvedParty:
          $ref: "#/components/schemas/StatusInvolvedParty"
    StatusInvolvedParty:
      type: object
      description: Party involved in lifecycle status
      properties:
        PartyInvolvement:
          $ref: "#/components/schemas/PartyInvolvement"
        PartyRoleName:
          $ref: "#/components/schemas/PartyRoleName"
    PartyInvolvement:
      type: object
      description: Party role involvement
      properties:
        PartyRoleType:
          type: string
          description: Party Role Type
          maxLength: 2
          enum: [O,S,M,I]
          example: O
    PartyRoleName:
      type: object
      description: Role name for a party
      properties:
        Name:
          type: integer
          description: Numeric name of role
          example: 2001
